name: Terraform CI CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-infra:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::339713176056:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform-VPC

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./Terraform-VPC

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Terraform-VPC

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ./Terraform-VPC